# Generated by Django 3.0.8 on 2020-07-22 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctype', models.CharField(choices=[('PASS', 'passport'), ('DVLS', 'driving licence')], max_length=4)),
                ('filetype', models.CharField(choices=[('PDF', 'PDF'), ('IMG', 'Image')], max_length=3)),
                ('access', models.CharField(choices=[('TEXT', 'File Extracted'), ('FILE', 'File Stored')], max_length=4)),
                ('location', models.CharField(max_length=47)),
                ('hashcode', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=47)),
                ('dob', models.DateField()),
                ('permanent', models.TextField()),
                ('current', models.TextField()),
                ('docs', models.ManyToManyField(to='api.Document')),
                ('links', models.ManyToManyField(related_name='_person_links_+', to='api.Person')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Person'),
        ),
    ]
