# Generated by Django 3.0.8 on 2020-07-25 03:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='uploaded',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='iden_type',
            field=models.CharField(blank=True, choices=[('PAS', 'passport'), ('DVL', 'driving licence'), ('PAN', 'pan card'), ('AAD', 'aadhar card')], max_length=3),
        ),
        migrations.AddField(
            model_name='person',
            name='iden_value',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='person',
            name='key',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='access',
            field=models.CharField(choices=[('TEXT', 'File Processed'), ('FILE', 'File Stored'), ('BOTH', 'File Stored and Processed')], max_length=4),
        ),
        migrations.AlterField(
            model_name='document',
            name='doctype',
            field=models.CharField(choices=[('PAS', 'passport'), ('DVL', 'driving licence'), ('PAN', 'pan card'), ('AAD', 'aadhar card')], max_length=3),
        ),
        migrations.AlterUniqueTogether(
            name='document',
            unique_together={('doctype', '_person')},
        ),
    ]
