# Generated by Django 3.0.8 on 2020-07-28 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200725_0304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=47)),
                ('password', models.CharField(max_length=47)),
                ('usertype', models.CharField(choices=[('ADM', 'admin'), ('USR', 'user')], max_length=3)),
                ('recovery', models.EmailField(max_length=254)),
                ('linked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Person')),
            ],
        ),
    ]
